server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    #url: jdbc:mysql://172.0.0.1:3306/hmdp?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.150.130
    port: 6379
#    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段 JSON只序列化非null属性
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包 包下实体类做mapper配置不用写全类名
logging:
  level:
    com.hmdp: debug